<?php
// module/Job/view/Job/Job/delete.phtml:

$title = 'Delete job';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($job->title); ?>' by
    '<?php echo $this->escapeHtml($job->companyName); ?>'?
</p>
<?php
$url = $this->url('job/delete/4', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $job->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>