<?php
// module/Job/view/Job/category/delete.phtml:

$title = 'Delete category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($category->cat_id); ?>' by
    '<?php echo $this->escapeHtml($category->cat_name); ?>'?
</p>
<?php
$url = $this->url('category/delete', array(
    'action' => 'delete',
    'id'     => $this->cat_id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="cat_id" value="<?php echo (int) $category->cat_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>