<?php
// module/Job/view/job/Category/edit.phtml:
$title = 'Edit Category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'category/edit',
   array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
echo '<div class="label">';
echo '<h2 class ="ui-widget-header">';
    echo $this->escapeHtml($title);
echo '</h2>';
echo $this->form()->openTag($form);

 echo '<div class="control-group">';
    echo '<label class="control-label">Category:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('cat_name'));
        echo '</div>';
    echo '</div>';

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '</div>';