<?php
// module/Job/view/Job/Subject/index.phtml:

$title = 'My Subject';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table table-hover">
<tbody>

<?php 
foreach ($subjects as $subject) :?>
    <tr>
    <td><?php echo $this->escapeHtml($subject->com_cat_id);?></td>
    <td><?php echo $this->escapeHtml($subject->sub_name);?></td>
    <td><?php echo $this->escapeHtml($subject->percentage);?></td>
	<td>
        <!-- edit and edit subject -->
        <a href="<?php echo $this->url('subject/edit',array(
            'action'=>'edit', 'id' => $subject->sub_id));?>">Edit</a>
       
        <a href="<?php echo $this->url('subject/delete',array(
            'action'=>'delete', 'id' => $subject->sub_id));?>">Delete</a>   
    </td>
    </tr>
    
<?php endforeach; ?>
   
    </tbody>
</table>

   <p>
    <a href="<?php echo $this->url('subject/add', array('action'=>'add'));?>">Add new subject</a>
</p>
    
   
 
    
    
    
        