<?php
// module/Job/view/Job/Subject/delete.phtml:

$title = 'Delete subject';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($subject->sub_id); ?>' by
    '<?php echo $this->escapeHtml($subject->sub_name); ?>'?
</p>
<?php
$url = $this->url('subject/delete', array(
    'action' => 'delete',
    'id'     => $this->sub_id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="sub_id" value="<?php echo (int) $subject->sub_id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>