<?php
// module/Job/view/Job/Pecentage/index.phtml:

$title = 'My pecentage';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

    
<?php foreach ($percentages as $per) { ?>
   <?php $percentage = $this->escapeHtml($per->percentage) ?>
    
    <?php if($percentage >= 75){ ?>
        <div class="progress progress-danger"> 
            <div class="bar" style="width: <?php echo $percentage.'%'; ?>">
                <?php echo $this->escapeHtml($per->sub_id).' ('.$percentage.'%)';?>
            </div>
        </div>   
   <?php } elseif ( $percentage >=50 ) { ?>   
    <div class="progress progress-warning"> 
            <div class="bar" style="width: <?php echo $percentage.'%'; ?>">
                <?php echo $this->escapeHtml($per->sub_id).' ('.$percentage.'%)';?>
            </div>
        </div>
   <?php } elseif ($percentage >= 25) { ?>
    <div class="progress progress-success"> 
            <div class="bar" style="width: <?php echo $percentage.'%'; ?>">
                <?php echo $this->escapeHtml($per->sub_id).' ('.$percentage.'%)';?>
            </div>
        </div>
   <?php }  else { ?>
    <div class="progress progress-info"> 
            <div class="bar" style="width: <?php echo $percentage.'%'; ?>">
                <?php echo $this->escapeHtml($per->sub_id).' ('.$percentage.'%)';?>
            </div>
        </div>    
   <?php } ?>
  <?php }?> 
    </tbody>

   <p>
    <a href="<?php echo $this->url('percentage/add', array('action'=>'add'));?>">Add new percentage</a>
</p>    

