<h2>Jobs detail of <?php echo $this->escapeHtml($details->companyName);?> company  </h2>
    <p>job detail</p>
    <?php echo 'Title :'. $this->escapeHtml($details->title);?> <br />
    <?php echo 'Company name:'. $this->escapeHtml($details->companyName);?><br />
    <?php echo 'Close date:'. $this->escapeHtml($details->closeDate);?><br />
    <?php echo 'Message:'. $this->escapeHtml($details->message);?><br />
    <?php echo 'Phone number:'.$this->escapeHtml($details->phoneNumber);?><br />
    <?php echo 'Email :'. $this->escapeHtml($details->email);?><br />
    <?php echo 'web :'. $this->escapeHtml($details->web);?><br />


