<?php
// module/Job/view/Job/Jobcategory/add.phtml:

$title = 'Add new job';
$this->headTitle($title);
?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('jobs/add', array('action' => 'add')));
$form->prepare();

echo '<div class="label">';
echo '<h2 class ="ui-widget-header">';
    echo $this->escapeHtml($title);
echo '</h2>';

echo $this->form()->openTag($form); 

echo '<div class="control-group">';
    echo '<label class="control-label">company id:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('com_id'));
        echo '</div>';
    echo '</div>';
    
     echo '<div class="control-group">';
    echo '<label class="control-label">category id:</label>';
        echo '<div class="controls">';   
        
        echo '<select name="cat_id">';
        foreach ($dd['categories'] as $category) : ?>
        <option  value=" <?php echo $this->escapeHtml($category->cat_id); ?> "> <?php echo $this->escapeHtml($category->cat_name); ?> </option>
        <?php endforeach;
        echo '</select>';
    
    echo '</div>';
    echo '</div>';
//echo '<div class="control-group">';
//    echo '<label class="control-label">job category id:</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('jcat_id'));
//        echo '</div>';
//    echo '</div>';
       
    echo '<div class="control-group">';
    echo '<label class="control-label">job deadline:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('job_deadline'));
        echo '</div>';
    echo '</div>';
    
  echo '<div class="control-group">';
    echo '<label class="control-label">job description:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('job_description'));
        echo '</div>';
    echo '</div>';
    
    
     
   echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '</div>';
    ?>
<script type="text/javaScript">
    $(function() {
     $(".datepicker").datepicker();
   });
</script>>