<?php
// module/Job/view/job/Job/edit.phtml:
$title = 'Edit Job';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'jobs/edit',
   array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
echo '<div class="label">';
echo '<h2 class ="ui-widget-header">';
    echo $this->escapeHtml($title);
echo '</h2>';
echo $this->form()->openTag($form);
echo $this->formRow($form->get('job_id'));

// echo '<div class="control-group">';
//    echo '<label class="control-label">job category id:</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('jcat_id'));
//        echo '</div>';
//    echo '</div>';
    
//    echo '<div class="control-group">';
//    echo '<label class="control-label">Category id:</label>';
//        echo '<div class="controls">';
//            echo $this->formRow($form->get('cat_id'));
//        echo '</div>';
//    echo '</div>';
    echo '<div class="control-group">';
    echo '<label class="control-label">Job deadline:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('job_deadline'));
        echo '</div>';
    echo '</div>';
    
    echo '<div class="control-group">';
    echo '<label class="control-label">Job description:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('job_description'));
        echo '</div>';
    echo '</div>';

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '</div>';
?>
<script type="text/javaScript">
    $(function() {
     $(".datepicker").datepicker();
   });
</script>>