<?php
// module/Job/view/Job/Job/index.phtml:

$title = 'My job';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table table-hover">
<tbody>

<?php 
foreach ($jobs as $job) :?>
    <tr>
        <td><?php echo $this->escapeHtml($job->com_id);?></td>
        <td><?php echo $this->escapeHtml($job->cat_id);?></td>
        <td><?php echo $this->escapeHtml($job->job_deadline);?></td>
        <td><?php echo $this->escapeHtml($job->job_description);?></td>
	<td>
        <!-- edit and delete jobs -->
        <a href="<?php echo $this->url('jobs/edit',array(
            'action'=>'edit', 'id' => $job->job_id));?>">Edit</a>
       
        <a href="<?php echo $this->url('jobs/delete',array(
            'action'=>'delete', 'id' => $job->job_id));?>">Delete</a>   
    </td>
    </tr>
    
<?php endforeach; ?>
   
    </tbody>
</table>

   <p>
    <a href="<?php echo $this->url('jobs/add', array('action'=>'add'));?>">Add new job</a>
</p>


    <div class="progress progress-info">
    <div class="bar" style="width: 20%"></div>
    </div>
    <div class="progress progress-success">
    <div class="bar" style="width: 40%"></div>
    </div>
    <div class="progress progress-warning">
    <div class="bar" style="width: 60%"></div>
    </div>
    <div class="progress progress-danger">
    <div class="bar" style="width: 80%"></div>
    </div>

    <div class="progress progress-info progress-striped">
    <div class="bar" style="width: 20%"></div>
    </div>
    <div class="progress progress-success progress-striped">
    <div class="bar" style="width: 40%"></div>
    </div>
    <div class="progress progress-warning progress-striped">
    <div class="bar" style="width: 60%"></div>
    </div>
    <div class="progress progress-danger progress-striped">
    <div class="bar" style="width: 80%"></div>
    </div>
    

   

    
   
 
    
    
    
        