<?php
// module/Job/view/job/Category/edit.phtml:
$title = 'Edit Company';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'company/edit',
   array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
echo '<div class="label">';
echo '<h2 class ="ui-widget-header">';
    echo $this->escapeHtml($title);
echo '</h2>';
echo $this->form()->openTag($form);
echo $this->formRow($form->get('com_id'));
 echo '<div class="control-group">';
    echo '<label class="control-label">user id:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('user_id'));
        echo '</div>';
    echo '</div>';
    echo '<div class="control-group">';
    echo '<label class="control-label">approve:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('approve'));
        echo '</div>';
    echo '</div>';
    echo '<div class="control-group">';
    echo '<label class="control-label">company name:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('com_name'));
        echo '</div>';
    echo '</div>';
    echo '<div class="control-group">';
    echo '<label class="control-label">company location:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('com_location'));
        echo '</div>';
    echo '</div>';
    echo '<div class="control-group">';
    echo '<label class="control-label">Company email:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('com_email'));
        echo '</div>';
    echo '</div>';
    echo '<div class="control-group">';
    echo '<label class="control-label">Company web site:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('com_web'));
        echo '</div>';
    echo '</div>';

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '</div>';
?>
